import React from "react";

const Profile = () => {
    return (
        <div className="content">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas porta diam ut sapien feugiat laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquet quis massa at consequat. Quisque dignissim mi ut nulla efficitur faucibus. In nulla arcu, porttitor ac molestie ac, eleifend sed ipsum. Aenean volutpat tincidunt lacus quis pretium. Vivamus id mattis ipsum. Nullam egestas egestas mi pharetra luctus. In hac habitasse platea dictumst. Donec nisi sapien, cursus id viverra nec, gravida sed augue. In id iaculis enim. Sed risus erat, fringilla et pulvinar sit amet, porttitor et libero. Maecenas et neque sed nisi malesuada euismod id sed diam. Nulla tellus sapien, viverra at metus at, tincidunt viverra erat. Donec feugiat vitae tellus eget blandit. Nunc iaculis pellentesque arcu non convallis.

            Morbi pharetra libero et molestie suscipit. Etiam sollicitudin arcu a elementum bibendum. In mauris arcu, sollicitudin quis bibendum dictum, euismod a tortor. Etiam a neque quis eros commodo posuere in vel justo. Praesent suscipit libero vel mauris consectetur fringilla. Duis sed libero sit amet diam dictum fermentum ut et sapien. Maecenas quis pulvinar nisi. Morbi lectus velit, semper faucibus aliquet ornare, mattis non leo. In nisi mi, sodales ut vehicula vitae, dignissim at lectus. Quisque eu enim nec ipsum sagittis imperdiet in nec odio. Pellentesque a tincidunt lorem. Sed ante tortor, accumsan sit amet nulla eu, feugiat semper orci.

            In eleifend felis mauris, nec commodo justo blandit eu. Proin rutrum velit sed mattis rutrum. Nulla accumsan ex sem, eget dictum libero luctus eu. Cras id arcu eu est tempor mattis sed at orci. Quisque quis massa at lacus egestas sagittis sit amet mattis ipsum. Proin lobortis, sapien ut elementum lobortis, ligula felis rutrum nulla, vitae aliquam magna sapien eu elit. Donec metus elit, tincidunt auctor orci sed, auctor congue lacus. Vestibulum posuere mi at massa feugiat, vitae varius mi volutpat. Fusce vel ultrices nisi.

            Curabitur mattis nisi sagittis, sagittis purus ac, porttitor diam. Etiam nec feugiat diam. Nullam tempor turpis eu dolor molestie, et sodales lacus mattis. Sed maximus enim non convallis placerat. Donec porttitor mollis lacus non euismod. Integer fringilla semper diam. Mauris cursus magna sit amet felis finibus consectetur. In hac habitasse platea dictumst. Vivamus at dolor eu risus facilisis lacinia. Sed sed lorem quam. Morbi volutpat diam risus, vel tristique orci ornare vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin nec urna dolor. Sed non vulputate velit, in sagittis arcu. Morbi eu sollicitudin ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

            Etiam maximus risus a risus ornare, eu eleifend lacus vestibulum. Maecenas eget auctor urna. Ut ante eros, molestie vitae cursus imperdiet, volutpat vel odio. Praesent vel quam molestie magna imperdiet eleifend. Maecenas non volutpat nulla. Pellentesque erat ipsum, eleifend id pellentesque et, vehicula a urna. Nam non efficitur arcu. Quisque placerat, tortor et auctor ornare, purus est ultricies lectus, tempor scelerisque felis libero nec ante. Phasellus porttitor massa sem. In non tincidunt ipsum. Fusce rhoncus nec massa id consectetur. Nunc nulla odio, varius et magna ac, imperdiet faucibus sem. Vestibulum consequat nunc sed nulla ultrices, nec sollicitudin tortor lobortis.
        </div>
    )
}

export default Profile;